// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComercioApiRest.Models;

public partial class Articulo
{
    public int CodArticulo { get; set; }

    public string Nombre { get; set; }

    public decimal? PreUnitario { get; set; }

    
}