// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ComercioApiRest.Models;

public partial class DbContextComercio : DbContext
{
    public DbContextComercio(DbContextOptions<DbContextComercio> options)
        : base(options)
    {
    }

    public virtual DbSet<Articulo> Articulos { get; set; }

    public virtual DbSet<DetallesFactura> DetallesFacturas { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<FormasPago> FormasPagos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Articulo>(entity =>
        {
            entity.HasKey(e => e.CodArticulo).HasName("pk_articulo");

            entity.Property(e => e.CodArticulo).HasColumnName("cod_articulo");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.PreUnitario)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("pre_unitario");
        });

        modelBuilder.Entity<DetallesFactura>(entity =>
        {
            entity.HasKey(e => e.CodDetalleFactura).HasName("pk_detalleFactura");

            entity.Property(e => e.CodDetalleFactura)
                .ValueGeneratedNever()
                .HasColumnName("cod_detalleFactura");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.Articulo).HasColumnName("cod_articulo");
            entity.Property(e => e.Nro_Factura).HasColumnName("nro_factura");

            entity.HasOne<Articulo>()
                .WithMany()
                .HasForeignKey(d => d.Articulo)
                .HasConstraintName("fk_articulo");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.Nro_Factura).HasName("pk_factura");

            entity.Property(e => e.Nro_Factura).HasColumnName("nro_factura");
            entity.Property(e => e.Cliente)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("cliente");
            entity.Property(e => e.CodFormaPago).HasColumnName("cod_formaPago");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");

            entity.HasOne<FormasPago>()
                .WithMany()
                .HasForeignKey(d => d.CodFormaPago)
                .HasConstraintName("fk_formaPago");

            entity.HasMany(f => f.DetallesFacturas)
                .WithOne()
                .HasForeignKey(df => df.Nro_Factura)
                .HasConstraintName("fk_factura");
        });

        modelBuilder.Entity<FormasPago>(entity =>
        {
            entity.HasKey(e => e.CodFormaPago).HasName("pk_FormaPago");

            entity.ToTable("FormasPago");

            entity.Property(e => e.CodFormaPago).HasColumnName("cod_formaPago");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}