// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComercioApiRest.Models;

public partial class FormasPago
{
    public int CodFormaPago { get; set; }

    public string Descripcion { get; set; }

    
}