// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComercioApiRest.Models;

public partial class DetallesFactura
{
    public int CodDetalleFactura { get; set; }

    public int? NroFactura { get; set; }

    public int Articulo { get; set; } 

    public int? Cantidad { get; set; }
    
}