// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ComercioApiRest.Models;

public partial class Factura
{
    public int NroFactura { get; set; }

    public DateOnly? Fecha { get; set; }

    public int? CodFormaPago { get; set; }

    public string Cliente { get; set; }

    public ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();
}